modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "goldenberries"
version = "${version}"
displayName = "Golden Berries"
authors = "legoatoom"
description = '''
Adds golden berries to the game.
'''
logoFile = "assets/goldenberries/icon.png"

[[dependencies.goldenberries]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.goldenberries]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.goldenberries]]
modId = "architectury"
mandatory = true
versionRange = "[3.6.17,)"
ordering = "AFTER"
side = "BOTH"
