name: release-artifacts


on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version of the mod"
      mcVersion:
        required: true
        description: "Version of Minecraft"
      versionType:
        default: release
        options:
          - alpha
          - beta
          - release
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2.1.0
        with:
          distribution: zulu
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew clean build

      # Runs a set of commands using the runners shell
      - name: Publish Minecraft Mods
        # You may pin to the exact commit or the version.   
        uses: Kir-Antipov/mc-publish@v1.1
        with:
          github-tag: "${{github.event.input.version}}+${{github.event.input.mcVersion}}"
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar

          name: "Golden Berries ${{ github.event.input.version }} for Minecraft ${{ github.event.input.mcVersion }}"
          version: "${{github.event.input.version}}+${{github.event.input.mcVersion}}"
          versionType: ${{ github.event.inputs.versionType }}
          changelog-file: CHANGELOG.md

          loaders: fabric
          gameVersions: ${{github.event.input.mcVersion}}
          java: 17
